# Auto-generated sector mappings for S&P 500 + mid-caps
# Fetch via yfinance info endpoint

NEW_SECTOR_ENTRIES = {
    "A": ("Healthcare", "$XLV"),
    "ABNB": ("Consumer Discretionary", "$XLY"),
    "ACGL": ("Financials", "$XLF"),
    "ACN": ("Technology", "$XLK"),
    "ADI": ("Technology", "$XLK"),
    "ADM": ("Consumer Staples", "$XLP"),
    "ADP": ("Technology", "$XLK"),
    "ADSK": ("Technology", "$XLK"),
    "AEE": ("Utilities", "$XLU"),
    "AEP": ("Utilities", "$XLU"),
    "AES": ("Utilities", "$XLU"),
    "AFL": ("Financials", "$XLF"),
    "AIG": ("Financials", "$XLF"),
    "AIZ": ("Financials", "$XLF"),
    "AJG": ("Financials", "$XLF"),
    "AKAM": ("Technology", "$XLK"),
    "ALB": ("Materials", "$XLB"),
    "ALGN": ("Healthcare", "$XLV"),
    "ALL": ("Financials", "$XLF"),
    "ALLE": ("Industrials", "$XLI"),
    "AMCR": ("Consumer Discretionary", "$XLY"),
    "AME": ("Industrials", "$XLI"),
    "AMP": ("Financials", "$XLF"),
    "AON": ("Financials", "$XLF"),
    "AOS": ("Industrials", "$XLI"),
    "APA": ("Energy", "$XLE"),
    "APH": ("Technology", "$XLK"),
    "APO": ("Financials", "$XLF"),
    "APP": ("Communication Services", "$XLC"),
    "APTV": ("Consumer Discretionary", "$XLY"),
    "ARE": ("Real Estate", "$XLRE"),
    "ARES": ("Financials", "$XLF"),
    "ATO": ("Utilities", "$XLU"),
    "AVB": ("Real Estate", "$XLRE"),
    "AVY": ("Consumer Discretionary", "$XLY"),
    "AWK": ("Utilities", "$XLU"),
    "AXON": ("Industrials", "$XLI"),
    "AZO": ("Consumer Discretionary", "$XLY"),
    "BALL": ("Consumer Discretionary", "$XLY"),
    "BAX": ("Healthcare", "$XLV"),
    "BBY": ("Consumer Discretionary", "$XLY"),
    "BDX": ("Healthcare", "$XLV"),
    "BEN": ("Financials", "$XLF"),
    "BF-B": ("Consumer Staples", "$XLP"),
    "BG": ("Consumer Staples", "$XLP"),
    "BIIB": ("Healthcare", "$XLV"),
    "BKR": ("Energy", "$XLE"),
    "BLDR": ("Industrials", "$XLI"),
    "BNY": ("Financials", "$XLF"),
    "BR": ("Technology", "$XLK"),
    "BRK-B": ("Financials", "$XLF"),
    "BRO": ("Financials", "$XLF"),
    "BSX": ("Healthcare", "$XLV"),
    "BX": ("Financials", "$XLF"),
    "BXP": ("Real Estate", "$XLRE"),
    "CAH": ("Healthcare", "$XLV"),
    "CARR": ("Industrials", "$XLI"),
    "CASY": ("Consumer Discretionary", "$XLY"),
    "CBOE": ("Financials", "$XLF"),
    "CBRE": ("Real Estate", "$XLRE"),
    "CCI": ("Real Estate", "$XLRE"),
    "CCL": ("Consumer Discretionary", "$XLY"),
    "CDW": ("Technology", "$XLK"),
    "CEG": ("Utilities", "$XLU"),
    "CF": ("Materials", "$XLB"),
    "CFG": ("Financials", "$XLF"),
    "CHD": ("Consumer Staples", "$XLP"),
    "CHRW": ("Industrials", "$XLI"),
    "CHTR": ("Communication Services", "$XLC"),
    "CI": ("Healthcare", "$XLV"),
    "CIEN": ("Technology", "$XLK"),
    "CINF": ("Financials", "$XLF"),
    "CLX": ("Consumer Staples", "$XLP"),
    "CME": ("Financials", "$XLF"),
    "CMG": ("Consumer Discretionary", "$XLY"),
    "CMI": ("Industrials", "$XLI"),
    "CMS": ("Utilities", "$XLU"),
    "CNC": ("Healthcare", "$XLV"),
    "CNP": ("Utilities", "$XLU"),
    "COF": ("Financials", "$XLF"),
    "COHR": ("Technology", "$XLK"),
    "COIN": ("Financials", "$XLF"),
    "COO": ("Healthcare", "$XLV"),
    "COR": ("Healthcare", "$XLV"),
    "CPAY": ("Technology", "$XLK"),
    "CPRT": ("Industrials", "$XLI"),
    "CPT": ("Real Estate", "$XLRE"),
    "CRH": ("Materials", "$XLB"),
    "CRL": ("Healthcare", "$XLV"),
    "CRWD": ("Technology", "$XLK"),
    "CSGP": ("Real Estate", "$XLRE"),
    "CSX": ("Industrials", "$XLI"),
    "CTAS": ("Industrials", "$XLI"),
    "CTSH": ("Technology", "$XLK"),
    "CTVA": ("Materials", "$XLB"),
    "CVNA": ("Consumer Discretionary", "$XLY"),
    "CVS": ("Healthcare", "$XLV"),
    "D": ("Utilities", "$XLU"),
    "DAL": ("Industrials", "$XLI"),
    "DASH": ("Consumer Discretionary", "$XLY"),
    "DD": ("Materials", "$XLB"),
    "DDOG": ("Technology", "$XLK"),
    "DECK": ("Consumer Discretionary", "$XLY"),
    "DELL": ("Technology", "$XLK"),
    "DG": ("Consumer Staples", "$XLP"),
    "DGX": ("Healthcare", "$XLV"),
    "DHI": ("Consumer Discretionary", "$XLY"),
    "DLR": ("Real Estate", "$XLRE"),
    "DLTR": ("Consumer Staples", "$XLP"),
    "DOC": ("Real Estate", "$XLRE"),
    "DOV": ("Industrials", "$XLI"),
    "DOW": ("Materials", "$XLB"),
    "DPZ": ("Consumer Discretionary", "$XLY"),
    "DRI": ("Consumer Discretionary", "$XLY"),
    "DTE": ("Utilities", "$XLU"),
    "DVA": ("Healthcare", "$XLV"),
    "DVN": ("Energy", "$XLE"),
    "DXCM": ("Healthcare", "$XLV"),
    "EA": ("Communication Services", "$XLC"),
    "EBAY": ("Consumer Discretionary", "$XLY"),
    "ECHO": ("Communication Services", "$XLC"),
    "ECL": ("Materials", "$XLB"),
    "ED": ("Utilities", "$XLU"),
    "EFX": ("Industrials", "$XLI"),
    "EG": ("Financials", "$XLF"),
    "EIX": ("Utilities", "$XLU"),
    "EL": ("Consumer Staples", "$XLP"),
    "ELV": ("Healthcare", "$XLV"),
    "EME": ("Industrials", "$XLI"),
    "EMR": ("Industrials", "$XLI"),
    "EQIX": ("Real Estate", "$XLRE"),
    "EQR": ("Real Estate", "$XLRE"),
    "EQT": ("Energy", "$XLE"),
    "ERIE": ("Financials", "$XLF"),
    "ES": ("Utilities", "$XLU"),
    "ESS": ("Real Estate", "$XLRE"),
    "ETN": ("Industrials", "$XLI"),
    "ETR": ("Utilities", "$XLU"),
    "EVRG": ("Utilities", "$XLU"),
    "EW": ("Healthcare", "$XLV"),
    "EXC": ("Utilities", "$XLU"),
    "EXE": ("Energy", "$XLE"),
    "EXPD": ("Industrials", "$XLI"),
    "EXPE": ("Consumer Discretionary", "$XLY"),
    "EXR": ("Real Estate", "$XLRE"),
    "FANG": ("Energy", "$XLE"),
    "FAST": ("Industrials", "$XLI"),
    "FDS": ("Financials", "$XLF"),
    "FDX": ("Industrials", "$XLI"),
    "FDXF": ("Industrials", "$XLI"),
    "FE": ("Utilities", "$XLU"),
    "FFIV": ("Technology", "$XLK"),
    "FICO": ("Technology", "$XLK"),
    "FIS": ("Technology", "$XLK"),
    "FITB": ("Financials", "$XLF"),
    "FIX": ("Industrials", "$XLI"),
    "FLEX": ("Technology", "$XLK"),
    "FOX": ("Communication Services", "$XLC"),
    "FOXA": ("Communication Services", "$XLC"),
    "FRT": ("Real Estate", "$XLRE"),
    "FSLR": ("Technology", "$XLK"),
    "FTNT": ("Technology", "$XLK"),
    "FTV": ("Technology", "$XLK"),
    "GD": ("Industrials", "$XLI"),
    "GDDY": ("Technology", "$XLK"),
    "GEHC": ("Healthcare", "$XLV"),
    "GEN": ("Technology", "$XLK"),
    "GEV": ("Industrials", "$XLI"),
    "GIS": ("Consumer Staples", "$XLP"),
    "GL": ("Financials", "$XLF"),
    "GLW": ("Technology", "$XLK"),
    "GNRC": ("Industrials", "$XLI"),
    "GOOG": ("Communication Services", "$XLC"),
    "GPC": ("Consumer Discretionary", "$XLY"),
    "GPN": ("Industrials", "$XLI"),
    "GRMN": ("Technology", "$XLK"),
    "GWW": ("Industrials", "$XLI"),
    "HAL": ("Energy", "$XLE"),
    "HAS": ("Consumer Discretionary", "$XLY"),
    "HBAN": ("Financials", "$XLF"),
    "HCA": ("Healthcare", "$XLV"),
    "HIG": ("Financials", "$XLF"),
    "HII": ("Industrials", "$XLI"),
    "HLT": ("Consumer Discretionary", "$XLY"),
    "HONA": ("Industrials", "$XLI"),
    "HOOD": ("Financials", "$XLF"),
    "HPE": ("Technology", "$XLK"),
    "HPQ": ("Technology", "$XLK"),
    "HRL": ("Consumer Staples", "$XLP"),
    "HSIC": ("Healthcare", "$XLV"),
    "HST": ("Real Estate", "$XLRE"),
    "HSY": ("Consumer Staples", "$XLP"),
    "HUBB": ("Industrials", "$XLI"),
    "HUM": ("Healthcare", "$XLV"),
    "HWM": ("Industrials", "$XLI"),
    "IBKR": ("Financials", "$XLF"),
    "IBM": ("Technology", "$XLK"),
    "ICE": ("Financials", "$XLF"),
    "IDXX": ("Healthcare", "$XLV"),
    "IEX": ("Industrials", "$XLI"),
    "IFF": ("Materials", "$XLB"),
    "INCY": ("Healthcare", "$XLV"),
    "INTU": ("Technology", "$XLK"),
    "INVH": ("Real Estate", "$XLRE"),
    "IP": ("Consumer Discretionary", "$XLY"),
    "IQV": ("Healthcare", "$XLV"),
    "IR": ("Industrials", "$XLI"),
    "IRM": ("Real Estate", "$XLRE"),
    "ISRG": ("Healthcare", "$XLV"),
    "IT": ("Technology", "$XLK"),
    "ITW": ("Industrials", "$XLI"),
    "IVZ": ("Financials", "$XLF"),
    "J": ("Industrials", "$XLI"),
    "JBHT": ("Industrials", "$XLI"),
    "JBL": ("Technology", "$XLK"),
    "JCI": ("Industrials", "$XLI"),
    "JKHY": ("Technology", "$XLK"),
    "KDP": ("Consumer Staples", "$XLP"),
    "KEY": ("Financials", "$XLF"),
    "KEYS": ("Technology", "$XLK"),
    "KHC": ("Consumer Staples", "$XLP"),
    "KIM": ("Real Estate", "$XLRE"),
    "KKR": ("Financials", "$XLF"),
    "KLAC": ("Technology", "$XLK"),
    "KMI": ("Energy", "$XLE"),
    "KR": ("Consumer Staples", "$XLP"),
    "KVUE": ("Consumer Staples", "$XLP"),
    "L": ("Financials", "$XLF"),
    "LDOS": ("Technology", "$XLK"),
    "LEN": ("Consumer Discretionary", "$XLY"),
    "LH": ("Healthcare", "$XLV"),
    "LHX": ("Industrials", "$XLI"),
    "LII": ("Industrials", "$XLI"),
    "LITE": ("Technology", "$XLK"),
    "LNT": ("Utilities", "$XLU"),
    "LRCX": ("Technology", "$XLK"),
    "LULU": ("Consumer Discretionary", "$XLY"),
    "LUV": ("Industrials", "$XLI"),
    "LVS": ("Consumer Discretionary", "$XLY"),
    "LYB": ("Materials", "$XLB"),
    "LYV": ("Communication Services", "$XLC"),
    "MA": ("Financials", "$XLF"),
    "MAA": ("Real Estate", "$XLRE"),
    "MAR": ("Consumer Discretionary", "$XLY"),
    "MAS": ("Industrials", "$XLI"),
    "MCHP": ("Technology", "$XLK"),
    "MCK": ("Healthcare", "$XLV"),
    "MCO": ("Financials", "$XLF"),
    "MDT": ("Healthcare", "$XLV"),
    "MGM": ("Consumer Discretionary", "$XLY"),
    "MKC": ("Consumer Staples", "$XLP"),
    "MLM": ("Materials", "$XLB"),
    "MNST": ("Consumer Staples", "$XLP"),
    "MO": ("Consumer Staples", "$XLP"),
    "MOS": ("Materials", "$XLB"),
    "MPWR": ("Technology", "$XLK"),
    "MRNA": ("Healthcare", "$XLV"),
    "MRSH": ("Financials", "$XLF"),
    "MRVL": ("Technology", "$XLK"),
    "MSCI": ("Financials", "$XLF"),
    "MSI": ("Technology", "$XLK"),
    "MTB": ("Financials", "$XLF"),
    "MTD": ("Healthcare", "$XLV"),
    "NCLH": ("Consumer Discretionary", "$XLY"),
    "NDAQ": ("Financials", "$XLF"),
    "NDSN": ("Industrials", "$XLI"),
    "NI": ("Utilities", "$XLU"),
    "NOC": ("Industrials", "$XLI"),
    "NOW": ("Technology", "$XLK"),
    "NRG": ("Utilities", "$XLU"),
    "NSC": ("Industrials", "$XLI"),
    "NTAP": ("Technology", "$XLK"),
    "NTRS": ("Financials", "$XLF"),
    "NUE": ("Materials", "$XLB"),
    "NVR": ("Consumer Discretionary", "$XLY"),
    "NWS": ("Communication Services", "$XLC"),
    "NWSA": ("Communication Services", "$XLC"),
    "NXPI": ("Technology", "$XLK"),
    "O": ("Real Estate", "$XLRE"),
    "ODFL": ("Industrials", "$XLI"),
    "OHI": ("Real Estate", "$XLRE"),
    "OKE": ("Energy", "$XLE"),
    "OMC": ("Communication Services", "$XLC"),
    "ON": ("Technology", "$XLK"),
    "ORLY": ("Consumer Discretionary", "$XLY"),
    "OTIS": ("Industrials", "$XLI"),
    "PAYX": ("Technology", "$XLK"),
    "PCAR": ("Industrials", "$XLI"),
    "PCG": ("Utilities", "$XLU"),
    "PEG": ("Utilities", "$XLU"),
    "PFG": ("Financials", "$XLF"),
    "PGR": ("Financials", "$XLF"),
    "PH": ("Industrials", "$XLI"),
    "PHM": ("Consumer Discretionary", "$XLY"),
    "PKG": ("Consumer Discretionary", "$XLY"),
    "PLTR": ("Technology", "$XLK"),
    "PM": ("Consumer Staples", "$XLP"),
    "PNR": ("Industrials", "$XLI"),
    "PNW": ("Utilities", "$XLU"),
    "PODD": ("Healthcare", "$XLV"),
    "POST": ("Consumer Staples", "$XLP"),
    "PPG": ("Materials", "$XLB"),
    "PPL": ("Utilities", "$XLU"),
    "PRU": ("Financials", "$XLF"),
    "PSA": ("Real Estate", "$XLRE"),
    "PSKY": ("Communication Services", "$XLC"),
    "PTC": ("Technology", "$XLK"),
    "PWR": ("Industrials", "$XLI"),
    "PYPL": ("Financials", "$XLF"),
    "Q": ("Technology", "$XLK"),
    "RCL": ("Consumer Discretionary", "$XLY"),
    "REG": ("Real Estate", "$XLRE"),
    "REGN": ("Healthcare", "$XLV"),
    "RF": ("Financials", "$XLF"),
    "RJF": ("Financials", "$XLF"),
    "RL": ("Consumer Discretionary", "$XLY"),
    "RMD": ("Healthcare", "$XLV"),
    "ROK": ("Industrials", "$XLI"),
    "ROL": ("Consumer Discretionary", "$XLY"),
    "ROP": ("Technology", "$XLK"),
    "ROST": ("Consumer Discretionary", "$XLY"),
    "RSG": ("Industrials", "$XLI"),
    "RVTY": ("Healthcare", "$XLV"),
    "SBAC": ("Real Estate", "$XLRE"),
    "SJM": ("Consumer Staples", "$XLP"),
    "SMCI": ("Technology", "$XLK"),
    "SNA": ("Industrials", "$XLI"),
    "SNDK": ("Technology", "$XLK"),
    "SOLV": ("Healthcare", "$XLV"),
    "SPG": ("Real Estate", "$XLRE"),
    "SRE": ("Utilities", "$XLU"),
    "STE": ("Healthcare", "$XLV"),
    "STLD": ("Materials", "$XLB"),
    "STT": ("Financials", "$XLF"),
    "STX": ("Technology", "$XLK"),
    "SW": ("Consumer Discretionary", "$XLY"),
    "SWK": ("Industrials", "$XLI"),
    "SWKS": ("Technology", "$XLK"),
    "SYF": ("Financials", "$XLF"),
    "SYK": ("Healthcare", "$XLV"),
    "SYY": ("Consumer Staples", "$XLP"),
    "TAP": ("Consumer Staples", "$XLP"),
    "TDG": ("Industrials", "$XLI"),
    "TDY": ("Technology", "$XLK"),
    "TECH": ("Healthcare", "$XLV"),
    "TEL": ("Technology", "$XLK"),
    "TER": ("Technology", "$XLK"),
    "TFC": ("Financials", "$XLF"),
    "TKO": ("Communication Services", "$XLC"),
    "TMUS": ("Communication Services", "$XLC"),
    "TPL": ("Energy", "$XLE"),
    "TPR": ("Consumer Discretionary", "$XLY"),
    "TRGP": ("Energy", "$XLE"),
    "TRMB": ("Technology", "$XLK"),
    "TROW": ("Financials", "$XLF"),
    "TRV": ("Financials", "$XLF"),
    "TSCO": ("Consumer Discretionary", "$XLY"),
    "TSN": ("Consumer Staples", "$XLP"),
    "TT": ("Industrials", "$XLI"),
    "TTD": ("Communication Services", "$XLC"),
    "TTWO": ("Communication Services", "$XLC"),
    "TXT": ("Industrials", "$XLI"),
    "TYL": ("Technology", "$XLK"),
    "UAL": ("Industrials", "$XLI"),
    "UBER": ("Technology", "$XLK"),
    "UDR": ("Real Estate", "$XLRE"),
    "UHS": ("Healthcare", "$XLV"),
    "ULTA": ("Consumer Discretionary", "$XLY"),
    "UNP": ("Industrials", "$XLI"),
    "URI": ("Industrials", "$XLI"),
    "V": ("Financials", "$XLF"),
    "VEEV": ("Healthcare", "$XLV"),
    "VICI": ("Real Estate", "$XLRE"),
    "VLO": ("Energy", "$XLE"),
    "VLTO": ("Industrials", "$XLI"),
    "VMC": ("Materials", "$XLB"),
    "VRSK": ("Industrials", "$XLI"),
    "VRSN": ("Technology", "$XLK"),
    "VRT": ("Industrials", "$XLI"),
    "VRTX": ("Healthcare", "$XLV"),
    "VST": ("Utilities", "$XLU"),
    "VTR": ("Real Estate", "$XLRE"),
    "VTRS": ("Healthcare", "$XLV"),
    "WAB": ("Industrials", "$XLI"),
    "WAT": ("Healthcare", "$XLV"),
    "WBD": ("Communication Services", "$XLC"),
    "WDAY": ("Technology", "$XLK"),
    "WDC": ("Technology", "$XLK"),
    "WEC": ("Utilities", "$XLU"),
    "WELL": ("Real Estate", "$XLRE"),
    "WM": ("Industrials", "$XLI"),
    "WMB": ("Energy", "$XLE"),
    "WRB": ("Financials", "$XLF"),
    "WSM": ("Consumer Discretionary", "$XLY"),
    "WST": ("Healthcare", "$XLV"),
    "WTW": ("Financials", "$XLF"),
    "WY": ("Real Estate", "$XLRE"),
    "WYNN": ("Consumer Discretionary", "$XLY"),
    "XEL": ("Utilities", "$XLU"),
    "XYL": ("Industrials", "$XLI"),
    "XYZ": ("Technology", "$XLK"),
    "YUM": ("Consumer Discretionary", "$XLY"),
    "ZBH": ("Healthcare", "$XLV"),
    "ZBRA": ("Technology", "$XLK"),
    "ZTS": ("Healthcare", "$XLV"),
}
